name: Weekly Reports
on:
  schedule:
    - cron: '0 9 * * 1' # Run at 9 AM every Monday
jobs:
  send-weekly-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Send weekly reports - Batch 1
        run: |
          curl --request POST \
          --url '${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/send-scheduled-reports?frequency=weekly&batch=0' \
          --header 'Authorization: Bearer ${{ secrets.REPORTS_API_KEY }}'
      
      - name: Wait for 5 minutes
        run: sleep 300
      
      - name: Send weekly reports - Batch 2
        run: |
          curl --request POST \
          --url '${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/send-scheduled-reports?frequency=weekly&batch=1' \
          --header 'Authorization: Bearer ${{ secrets.REPORTS_API_KEY }}'
      
      - name: Wait for 5 minutes
        run: sleep 300
      
      - name: Send weekly reports - Batch 3
        run: |
          curl --request POST \
          --url '${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/send-scheduled-reports?frequency=weekly&batch=2' \
          --header 'Authorization: Bearer ${{ secrets.REPORTS_API_KEY }}'
