name: Weekly Reports
on:
  schedule:
    - cron: '0 9 * * 1' # Run at 9 AM every Monday
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Weekly reports - Batch 1
        run: |
          curl --request POST \
          --url '${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/send-scheduled-reports' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.REPORTS_API_KEY }}' \
          --data '{"frequency": "weekly", "batch": 0}'
      
      - name: Wait for 5 minutes
        run: sleep 300
      
      - name: Weekly reports - Batch 2
        run: |
          curl --request POST \
          --url '${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/send-scheduled-reports' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.REPORTS_API_KEY }}' \
          --data '{"frequency": "weekly", "batch": 1}'
      
      - name: Wait for 5 minutes
        run: sleep 300
      
      - name: Weekly reports - Batch 3
        run: |
          curl --request POST \
          --url '${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/send-scheduled-reports' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.REPORTS_API_KEY }}' \
          --data '{"frequency": "weekly", "batch": 2}'
